{"uuid": "294719d5-eae5-409d-a280-f29cd9719db5", "children": ["ffe95d68-a19f-4a53-b293-61c97e3ed62e", "0c83474d-205d-41a0-a7a6-47f8d89bf4f5"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: permission denied\n\n", "trace": "  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\unittest.py\", line 99, in fixture\n    setup()\n  File \"C:\\Users\\17327\\PycharmProjects\\yunhe\\scripts\\test_out_manage.py\", line 12, in setUpClass\n    cls.driver = GetDriver().get_driver()\n  File \"C:\\Users\\17327\\PycharmProjects\\yunhe\\base\\get_driver.py\", line 11, in get_driver\n    cls.driver = webdriver.Firefox()\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    keep_alive=True)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1591170283984, "stop": 1591170296886}], "start": 1591170283984, "stop": 1591170297144}